spring:
  profiles:
    active: "develop"

zuul:
  routes:
    microservice-ili:
      service-id: st-microservice-ili
      path: /api/ili/**
      strip-prefix: false

---
spring:
  profiles: develop
  servlet:
    multipart:
      maxFileSize: 250MB
      maxRequestSize: 250MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
            
ribbon:
  ConnectTimeout: 40000
  ReadTimeout: 80000

server:
  port: 8090

---
spring:
  profiles: production
  servlet:
    multipart:
      maxFileSize: 250MB
      maxRequestSize: 250MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
            
ribbon:
  ConnectTimeout: 40000
  ReadTimeout: 80000

server:
  port: 8091
